// بيانات المنتجات - الطفل المبدع
export const products = [
  {
    id: 1,
    name: 'مكعبات البناء الخشبية الملونة - 100 قطعة',
    slug: 'wooden-building-blocks-100',
    description: 'مكعبات بناء خشبية طبيعية ملونة بألوان آمنة للأطفال. تساعد على تنمية المهارات الحركية الدقيقة والتفكير المكاني والإبداع. مصنوعة من خشب الزان الطبيعي عالي الجودة.',
    shortDescription: 'مكعبات خشبية تعليمية لتنمية الإبداع',
    price: 299,
    oldPrice: 399,
    category: 'building-toys',
    categoryName: 'ألعاب البناء',
    rating: 4.9,
    reviews: 128,
    stock: 50,
    images: [
      '/images/products/wooden-blocks-1.jpg',
      '/images/products/wooden-blocks-2.jpg',
      '/images/products/wooden-blocks-3.jpg',
    ],
    features: [
      '100 قطعة متنوعة الأشكال والألوان',
      'خشب زان طبيعي 100%',
      'ألوان مائية آمنة غير سامة',
      'حواف مصقولة لحماية الطفل',
      'حقيبة تخزين قماشية',
    ],
    ageRange: { min: 3, max: 8 },
    isNew: true,
    isFeatured: true,
    discount: 25,
    sku: 'WB-100-COL',
    weight: '2.5 كجم',
    dimensions: '30 × 25 × 15 سم',
    material: 'خشب زان طبيعي',
    brand: 'الطفل المبدع',
    tags: ['مكعبات', 'خشب', 'بناء', 'تعليمي', 'مونتيسوري'],
  },
  {
    id: 2,
    name: 'بازل خشبي تعليمي - الحروف العربية',
    slug: 'arabic-letters-puzzle',
    description: 'بازل خشبي تعليمي للحروف العربية مع صور توضيحية لكل حرف. يساعد الطفل على تعلم الحروف العربية بطريقة ممتعة وتفاعلية. مناسب لمرحلة ما قبل المدرسة.',
    shortDescription: 'بازل الحروف العربية التعليمي',
    price: 180,
    oldPrice: 220,
    category: 'educational-toys',
    categoryName: 'ألعاب تعليمية',
    rating: 4.8,
    reviews: 203,
    stock: 75,
    images: [
      '/images/products/arabic-puzzle-1.jpg',
      '/images/products/arabic-puzzle-2.jpg',
    ],
    features: [
      '28 حرف عربي',
      'صور توضيحية ملونة',
      'خشب MDF عالي الجودة',
      'طباعة مقاومة للخدش',
      'مقابض سهلة للأطفال',
    ],
    ageRange: { min: 2, max: 6 },
    isNew: false,
    isFeatured: true,
    discount: 18,
    sku: 'PZ-AR-28',
    weight: '0.8 كجم',
    dimensions: '40 × 30 × 2 سم',
    material: 'خشب MDF',
    brand: 'الطفل المبدع',
    tags: ['بازل', 'حروف عربية', 'تعليمي', 'لغة'],
  },
  {
    id: 3,
    name: 'لعبة الطبيب الصغير - مجموعة كاملة',
    slug: 'little-doctor-set',
    description: 'مجموعة أدوات الطبيب الكاملة للأطفال تشمل سماعة طبية وميزان حرارة ومقياس ضغط وأدوات أخرى. تساعد على تنمية مهارات لعب الأدوار والتعاطف.',
    shortDescription: 'مجموعة الطبيب التعليمية للأطفال',
    price: 280,
    oldPrice: 350,
    category: 'role-play',
    categoryName: 'ألعاب الأدوار',
    rating: 4.7,
    reviews: 167,
    stock: 40,
    images: [
      '/images/products/doctor-set-1.jpg',
      '/images/products/doctor-set-2.jpg',
    ],
    features: [
      '15 قطعة متنوعة',
      'سماعة طبية حقيقية الصوت',
      'حقيبة طبيب أنيقة',
      'بلاستيك ABS آمن',
      'ألوان زاهية جذابة',
    ],
    ageRange: { min: 3, max: 8 },
    isNew: true,
    isFeatured: true,
    discount: 20,
    sku: 'RP-DOC-15',
    weight: '0.6 كجم',
    dimensions: '25 × 20 × 10 سم',
    material: 'بلاستيك ABS آمن',
    brand: 'الطفل المبدع',
    tags: ['طبيب', 'لعب أدوار', 'تعليمي', 'مهارات اجتماعية'],
  },
  {
    id: 4,
    name: 'لوحة الرسم المغناطيسية الكبيرة',
    slug: 'magnetic-drawing-board-large',
    description: 'لوحة رسم مغناطيسية كبيرة الحجم مع أختام وقلم مغناطيسي. سهلة المسح وإعادة الاستخدام. تنمي مهارات الرسم والإبداع دون فوضى الألوان.',
    shortDescription: 'لوحة رسم مغناطيسية للأطفال',
    price: 150,
    oldPrice: 200,
    category: 'arts-crafts',
    categoryName: 'فنون وحرف',
    rating: 4.6,
    reviews: 156,
    stock: 60,
    images: [
      '/images/products/magnetic-board-1.jpg',
      '/images/products/magnetic-board-2.jpg',
    ],
    features: [
      'شاشة رسم كبيرة 30×20 سم',
      '4 أختام مغناطيسية',
      'قلم مغناطيسي مريح',
      'ممحاة سحب سهلة',
      'إطار ملون جذاب',
    ],
    ageRange: { min: 2, max: 7 },
    isNew: false,
    isFeatured: true,
    discount: 25,
    sku: 'AR-MAG-L',
    weight: '0.5 كجم',
    dimensions: '40 × 30 × 3 سم',
    material: 'بلاستيك ABS',
    brand: 'الطفل المبدع',
    tags: ['رسم', 'مغناطيسي', 'فنون', 'إبداع'],
  },
  {
    id: 5,
    name: 'مجموعة الصلصال الآمن - 12 لون',
    slug: 'safe-playdough-12-colors',
    description: 'صلصال آمن للأطفال مصنوع من مواد طبيعية غير سامة. 12 لون زاهي مع قوالب وأدوات تشكيل. ينمي المهارات الحركية الدقيقة والإبداع.',
    shortDescription: 'صلصال آمن متعدد الألوان',
    price: 120,
    oldPrice: 150,
    category: 'arts-crafts',
    categoryName: 'فنون وحرف',
    rating: 4.8,
    reviews: 189,
    stock: 100,
    images: [
      '/images/products/playdough-1.jpg',
      '/images/products/playdough-2.jpg',
    ],
    features: [
      '12 لون مختلف',
      'مواد طبيعية 100%',
      'غير سام وآمن للأطفال',
      '6 قوالب تشكيل',
      '4 أدوات تشكيل',
    ],
    ageRange: { min: 2, max: 8 },
    isNew: true,
    isFeatured: false,
    discount: 20,
    sku: 'AR-PLY-12',
    weight: '0.8 كجم',
    dimensions: '25 × 20 × 8 سم',
    material: 'مواد طبيعية آمنة',
    brand: 'الطفل المبدع',
    tags: ['صلصال', 'فنون', 'تشكيل', 'آمن'],
  },
  {
    id: 6,
    name: 'سيارة تحكم عن بعد للأطفال',
    slug: 'kids-remote-control-car',
    description: 'سيارة تحكم عن بعد مصممة خصيصاً للأطفال بأزرار كبيرة وسهلة الاستخدام. سرعة مناسبة وآمنة للأطفال الصغار.',
    shortDescription: 'سيارة ريموت كنترول للصغار',
    price: 350,
    oldPrice: 450,
    category: 'electronic-toys',
    categoryName: 'ألعاب إلكترونية',
    rating: 4.5,
    reviews: 72,
    stock: 30,
    images: [
      '/images/products/rc-car-1.jpg',
      '/images/products/rc-car-2.jpg',
    ],
    features: [
      'ريموت كنترول سهل الاستخدام',
      'سرعة آمنة للأطفال',
      'أضواء LED ملونة',
      'أصوات محرك واقعية',
      'بطارية قابلة للشحن',
    ],
    ageRange: { min: 3, max: 8 },
    isNew: false,
    isFeatured: true,
    discount: 22,
    sku: 'EL-RC-01',
    weight: '0.7 كجم',
    dimensions: '25 × 15 × 12 سم',
    material: 'بلاستيك ABS',
    brand: 'الطفل المبدع',
    tags: ['سيارة', 'ريموت', 'إلكتروني'],
  },
  {
    id: 7,
    name: 'خيمة اللعب للأطفال - قلعة الأميرة',
    slug: 'princess-castle-play-tent',
    description: 'خيمة لعب على شكل قلعة الأميرة بتصميم ساحر. سهلة التركيب والطي. توفر مساحة خاصة للعب والخيال.',
    shortDescription: 'خيمة لعب قلعة الأميرة',
    price: 450,
    oldPrice: 550,
    category: 'outdoor-toys',
    categoryName: 'ألعاب خارجية',
    rating: 4.9,
    reviews: 95,
    stock: 25,
    images: [
      '/images/products/tent-1.jpg',
      '/images/products/tent-2.jpg',
    ],
    features: [
      'تصميم قلعة ساحر',
      'قماش بوليستر متين',
      'سهلة التركيب والطي',
      'نوافذ شبكية للتهوية',
      'باب قابل للربط',
    ],
    ageRange: { min: 3, max: 10 },
    isNew: true,
    isFeatured: true,
    discount: 18,
    sku: 'OD-TNT-PR',
    weight: '1.5 كجم',
    dimensions: '120 × 120 × 140 سم',
    material: 'بوليستر وفايبرجلاس',
    brand: 'الطفل المبدع',
    tags: ['خيمة', 'لعب', 'خارجي', 'أميرة'],
  },
  {
    id: 8,
    name: 'مجموعة المطبخ الصغير',
    slug: 'mini-kitchen-set',
    description: 'مجموعة مطبخ كاملة للأطفال تشمل موقد وحوض وأدوات طبخ. تنمي مهارات لعب الأدوار والتخيل.',
    shortDescription: 'مطبخ لعب للأطفال',
    price: 650,
    oldPrice: 800,
    category: 'role-play',
    categoryName: 'ألعاب الأدوار',
    rating: 4.8,
    reviews: 134,
    stock: 20,
    images: [
      '/images/products/kitchen-1.jpg',
      '/images/products/kitchen-2.jpg',
    ],
    features: [
      'موقد بأضواء وأصوات',
      'حوض مع صنبور متحرك',
      '20 قطعة أدوات مطبخ',
      'خزائن للتخزين',
      'ارتفاع مناسب للأطفال',
    ],
    ageRange: { min: 3, max: 8 },
    isNew: false,
    isFeatured: true,
    discount: 19,
    sku: 'RP-KIT-01',
    weight: '5 كجم',
    dimensions: '60 × 30 × 80 سم',
    material: 'خشب MDF وبلاستيك',
    brand: 'الطفل المبدع',
    tags: ['مطبخ', 'لعب أدوار', 'طبخ'],
  },
  {
    id: 9,
    name: 'دمية ناطقة بالعربية - سارة',
    slug: 'arabic-talking-doll-sara',
    description: 'دمية تفاعلية ناطقة بالعربية الفصحى. تعلم الطفل الحروف والأرقام والأناشيد. مصنوعة من قماش ناعم وآمن.',
    shortDescription: 'دمية تعليمية ناطقة بالعربية',
    price: 380,
    oldPrice: 450,
    category: 'dolls',
    categoryName: 'دمى وعرائس',
    rating: 4.7,
    reviews: 89,
    stock: 35,
    images: [
      '/images/products/doll-1.jpg',
      '/images/products/doll-2.jpg',
    ],
    features: [
      'تنطق بالعربية الفصحى',
      'تعلم الحروف والأرقام',
      '10 أناشيد تعليمية',
      'قماش ناعم وآمن',
      'بطاريات قابلة للتبديل',
    ],
    ageRange: { min: 1, max: 6 },
    isNew: true,
    isFeatured: true,
    discount: 16,
    sku: 'DL-AR-SR',
    weight: '0.4 كجم',
    dimensions: '35 × 15 × 10 سم',
    material: 'قماش قطني وبوليستر',
    brand: 'الطفل المبدع',
    tags: ['دمية', 'ناطقة', 'عربي', 'تعليمي'],
  },
  {
    id: 10,
    name: 'لعبة الذاكرة - الحيوانات',
    slug: 'memory-game-animals',
    description: 'لعبة ذاكرة تعليمية بصور الحيوانات. تنمي الذاكرة والتركيز ومهارات المطابقة. 32 بطاقة بصور ملونة.',
    shortDescription: 'لعبة ذاكرة الحيوانات',
    price: 85,
    oldPrice: 100,
    category: 'puzzles',
    categoryName: 'ألغاز وتركيب',
    rating: 4.6,
    reviews: 145,
    stock: 80,
    images: [
      '/images/products/memory-1.jpg',
      '/images/products/memory-2.jpg',
    ],
    features: [
      '32 بطاقة (16 زوج)',
      'صور حيوانات ملونة',
      'كرتون سميك متين',
      'طباعة عالية الجودة',
      'علبة تخزين',
    ],
    ageRange: { min: 3, max: 8 },
    isNew: false,
    isFeatured: false,
    discount: 15,
    sku: 'PZ-MEM-AN',
    weight: '0.3 كجم',
    dimensions: '15 × 12 × 4 سم',
    material: 'كرتون مقوى',
    brand: 'الطفل المبدع',
    tags: ['ذاكرة', 'حيوانات', 'تركيز', 'بطاقات'],
  },
  {
    id: 11,
    name: 'عداد خشبي تعليمي - الأرقام',
    slug: 'wooden-abacus-numbers',
    description: 'عداد خشبي تعليمي لتعلم الأرقام والعد والحساب البسيط. ألوان زاهية وخرز خشبي آمن. أداة مونتيسوري كلاسيكية.',
    shortDescription: 'عداد خشبي لتعلم الحساب',
    price: 130,
    oldPrice: 160,
    category: 'educational-toys',
    categoryName: 'ألعاب تعليمية',
    rating: 4.8,
    reviews: 178,
    stock: 55,
    images: [
      '/images/products/abacus-1.jpg',
      '/images/products/abacus-2.jpg',
    ],
    features: [
      '10 صفوف × 10 خرزات',
      'خشب طبيعي آمن',
      'ألوان قوس قزح',
      'قاعدة ثابتة',
      'حجم مناسب للأطفال',
    ],
    ageRange: { min: 3, max: 8 },
    isNew: false,
    isFeatured: true,
    discount: 19,
    sku: 'ED-ABA-01',
    weight: '0.6 كجم',
    dimensions: '25 × 8 × 20 سم',
    material: 'خشب طبيعي',
    brand: 'الطفل المبدع',
    tags: ['عداد', 'حساب', 'أرقام', 'مونتيسوري'],
  },
  {
    id: 12,
    name: 'كرة القفز للأطفال مع مقبض',
    slug: 'hopper-ball-with-handle',
    description: 'كرة قفز مطاطية مع مقبض للإمساك. تنمي التوازن والتنسيق الحركي. مناسبة للعب داخل وخارج المنزل.',
    shortDescription: 'كرة قفز للنشاط الحركي',
    price: 95,
    oldPrice: 120,
    category: 'outdoor-toys',
    categoryName: 'ألعاب خارجية',
    rating: 4.5,
    reviews: 112,
    stock: 45,
    images: [
      '/images/products/hopper-1.jpg',
      '/images/products/hopper-2.jpg',
    ],
    features: [
      'مطاط عالي الجودة',
      'مقبض مريح وآمن',
      'مضخة هواء مرفقة',
      'ألوان متعددة',
      'يتحمل حتى 50 كجم',
    ],
    ageRange: { min: 3, max: 10 },
    isNew: false,
    isFeatured: false,
    discount: 21,
    sku: 'OD-HOP-01',
    weight: '0.5 كجم',
    dimensions: '45 سم قطر',
    material: 'مطاط PVC',
    brand: 'الطفل المبدع',
    tags: ['كرة', 'قفز', 'رياضة', 'توازن'],
  },
]

export const categories = [
  {
    id: 'educational-toys',
    name: 'ألعاب تعليمية',
    slug: 'educational-toys',
    description: 'ألعاب تنمي مهارات التفكير والتعلم والذكاء',
    image: '/images/categories/educational.jpg',
    icon: '📚',
    color: 'from-blue-400 to-blue-600',
    productCount: 45,
  },
  {
    id: 'building-toys',
    name: 'ألعاب البناء',
    slug: 'building-toys',
    description: 'مكعبات وألعاب بناء إبداعية للأطفال',
    image: '/images/categories/building.jpg',
    icon: '🧱',
    color: 'from-orange-400 to-orange-600',
    productCount: 32,
  },
  {
    id: 'dolls',
    name: 'دمى وعرائس',
    slug: 'dolls',
    description: 'دمى ناعمة وعرائس متنوعة للأطفال',
    image: '/images/categories/dolls.jpg',
    icon: '🧸',
    color: 'from-pink-400 to-pink-600',
    productCount: 28,
  },
  {
    id: 'electronic-toys',
    name: 'ألعاب إلكترونية',
    slug: 'electronic-toys',
    description: 'ألعاب تحكم عن بعد وإلكترونية تفاعلية',
    image: '/images/categories/electronic.jpg',
    icon: '🎮',
    color: 'from-purple-400 to-purple-600',
    productCount: 22,
  },
  {
    id: 'outdoor-toys',
    name: 'ألعاب خارجية',
    slug: 'outdoor-toys',
    description: 'ألعاب للحدائق والأماكن المفتوحة',
    image: '/images/categories/outdoor.jpg',
    icon: '⚽',
    color: 'from-green-400 to-green-600',
    productCount: 35,
  },
  {
    id: 'arts-crafts',
    name: 'فنون وحرف',
    slug: 'arts-crafts',
    description: 'أدوات رسم وتلوين وأعمال يدوية',
    image: '/images/categories/arts.jpg',
    icon: '🎨',
    color: 'from-red-400 to-red-600',
    productCount: 40,
  },
  {
    id: 'role-play',
    name: 'ألعاب الأدوار',
    slug: 'role-play',
    description: 'ألعاب تمثيل الأدوار والمهن',
    image: '/images/categories/roleplay.jpg',
    icon: '👨‍⚕️',
    color: 'from-teal-400 to-teal-600',
    productCount: 25,
  },
  {
    id: 'puzzles',
    name: 'ألغاز وتركيب',
    slug: 'puzzles',
    description: 'بازل وألعاب ذكاء وتركيب',
    image: '/images/categories/puzzles.jpg',
    icon: '🧩',
    color: 'from-indigo-400 to-indigo-600',
    productCount: 38,
  },
]

export const getProductById = (id) => products.find(p => p.id === parseInt(id))
export const getProductBySlug = (slug) => products.find(p => p.slug === slug)
export const getProductsByCategory = (categoryId) => products.filter(p => p.category === categoryId)
export const getFeaturedProducts = () => products.filter(p => p.isFeatured)
export const getNewProducts = () => products.filter(p => p.isNew)
export const getDiscountedProducts = () => products.filter(p => p.discount > 0)
